[project]
name = "django-govbrds"
version = "0.0.1"
description = "Design System do Governo Federal Brasileiro projetos derivados do Django"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
